### ISSUE TITLE
build-book-release R version update 

### ISSUE THREAD

**Issue by TuomasBorman** [microbiome/OMA#106]
Hi,

because of the latest Bioconductor release, latest Bioc requires R version 4.2 instead of 4.1.

R version of `build-book-release` must be changed

Info from build-book-release run
![image](https://user-images.githubusercontent.com/60338854/139264426-28867f9f-c468-4ec3-b8d3-b1cd7a993f4e.png)

-Tuomas

**Comment by TuomasBorman** [comment]
So we want Bioc version 3.14. 

I changed Bioc version from build-book-release.yml

line 58:

`cont: "bioconductor/bioconductor_docker:devel"`
to
`cont: "bioconductor/bioconductor_docker:RELEASE_3_14"`

This is not working, I took example from earlier commits

**Comment by TuomasBorman** [comment]
I think that I get this working

**Comment by FelixErnst** [comment]
In line 8 you also have to specify the R version

` - { os: ubuntu-latest, r: '4.1', cont: "bioconductor/bioconductor_docker:RELEASE_3_14", rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest" }`

**Comment by FelixErnst** [comment]
and line 102 you need specify the Bioc version 
`          BiocManager::install(version = "3.14", ask = FALSE)`

**Comment by TuomasBorman** [comment]
https://github.com/microbiome/OMA/pull/105/files

**Comment by TuomasBorman** [comment]
But now it's not running it

**Comment by FelixErnst** [comment]
You also need to change all `key` and `restore-key` values, bascially all devel values

**Comment by TuomasBorman** [comment]
Ok, thanks for the help. 

Apparently `RELEASE_3_14` docker is not available yet, but `latest` is so I used that. However, it seems that it does not contain `curatedMetagenomicData` package

`" there is no package called 'curatedMetagenomicData'"`

So do we have to wait `RELEASE_3_14`?

https://hub.docker.com/r/bioconductor/bioconductor_docker/tags

**Comment by FelixErnst** [comment]
Probably the data packages have not been all build, yet. I think it was build yesterday, maybe just after your run:

http://bioconductor.org/checkResults/release/data-experiment-LATEST/curatedMetagenomicData/

**Comment by FelixErnst** [comment]
Regarding the latest, yeah you can use that for now. With the call to `BiocManager` the correct version should be set. If latest gets update, you have to modify the setup again slightly

**Comment by TuomasBorman** [comment]
Fixed with commits

fcd73be18a11ef61da251128849c2a7a267b3f19
407f6b4fddf011be6fcaf448d1556dc76ecff273
20ce3792219d4ed08ccf0c5bf50e76cb61816680
39b1adb2f32f68536b41418a70a16ed0b7289fc0
57538ebdf8d047911b1498a608479b8a89a1a763
fd6cfce46d48e6626c66bf53791e42c646661efe
