### ISSUE TITLE
mia functionality

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#109]
Go through mia functionality and list which methods are yet to be included in OMA. Open issues as relevant.

**Comment by antagomir** [comment]
@jkc9886 could you check this?

**Comment by jkc9886** [comment]
Hello, sorry for this confusion, but where do I find mia functionality details? Is there a specific page we can find it? I am using the reference manual for mia from the Bioconductor website for it.

**Comment by antagomir** [comment]
mia homepage; see the reference tab
https://microbiome.github.io/mia/

**Comment by antagomir** [comment]
Have you identified mia methods that are not covered in OMA?

**Comment by jkc9886** [comment]
I went through the mia methods and I see almost all methods have been incorporated somewhere or the other in OMA, however I think the following functions/context (methods) are not used : 
1. Mediation Analysis : addMediation() getMediation()
2. Dirichlet-Multinomial Mixture Model: Machine Learning for Microbiome Data: calculateDMN() runDMN() getDMN() bestDMNFit() getBestDMNFit() calculateDMNgroup() performDMNgroupCV()

Please correct me if these have been deployed in any other ways?

Update : My mistake, The DMM methods have been included in the clustering Chapter, so I believe it is just the mediation analysis now.

**Comment by antagomir** [comment]
1. has its own issue #475 
2. DMMs are already dealt with in the clustering section
All good, thanks!
