### ISSUE TITLE
miaViz functionality

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#110]
Go through miaViz functionality and list which methods are yet to be included in OMA. Open issues as relevant.

**Comment by antagomir** [comment]
@jkc9886 could you check this?

**Comment by antagomir** [comment]
Have you identified miaViz methods that are not covered in OMA?

**Comment by jkc9886** [comment]
Based on the reference manual for miaViz, all methods have been included in OMA.

**Comment by antagomir** [comment]
awesome!
