### ISSUE TITLE
Significance in boxplots

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#115]
Add example on indicating significance betwen boxplots. 

There might be better options but [here is one](http://www.sthda.com/english/articles/24-ggpubr-publication-ready-plots/76-add-p-values-and-significance-levels-to-ggplots/)

Also check if (Tree)SE framework already has such visualizaiton tools readily available, and if not, consider if this should be added to *miaViz*.

**Comment by antagomir** [comment]
Is this solved? Seems related to #418

**Comment by ndegunst** [comment]
Seems like it's solved. It's not exactly like in the example. The user needs to specify the type of correction to use but it doesn't specify on the plot itself. Here's an example using the fdr method: 
![image](https://github.com/microbiome/OMA/assets/74536546/034f1391-5d76-491a-8591-a6ab51feb9ef)

**Comment by antagomir** [comment]
Ok handled in #439
