### ISSUE TITLE
getExperimentCrossCorrelation example

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#119]
`getExperimentCrossCorrelation` examples shall be added in OMA once the function has stabilized; consider a new sub/chapter for multiomics.

**Comment by TuomasBorman** [comment]
https://microbiome.github.io/OMA/multi-assay_analyses.html 

We already have dedicated chapter for that

**Comment by antagomir** [comment]
Ah, I thought so. Was momentarily in another local branch and missed.

The page has to be updated anyways, as the situation will allow.

**Comment by antagomir** [comment]
Perhaps @RiboRings could have a brief look if there are obvious things to improve?
