### ISSUE TITLE
Add subsection to 6.1 Alpha diversity for Faith’s (1992) index of phylogenetic diversity (PD)

### ISSUE THREAD

**Issue by microsud** [microbiome/OMA#12]
A widely used phylogenetic diversity in microbiome research that can be integrated in this book.

edit: Cannot assign it to myself... as I have limited access to this repo but I can add this sub-section if you are okay with it @antagomir @FelixErnst

**Comment by antagomir** [comment]
Yes very good. Faith index should definitely be there. Perhaps we should also add some permissions to you?

**Comment by FelixErnst** [comment]
I changed them an hour or so ago. Should work now

**Comment by microsud** [comment]
@FelixErnst Thanks. I will have a look :)

**Comment by FelixErnst** [comment]
See FelixErnst/mia#81

**Comment by FelixErnst** [comment]
The Faith's index is now implemented in `mia`

**Comment by microsud** [comment]
Thanks. Will update this as soon as possible :)
