### ISSUE TITLE
Add missing functions to OMA

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#120]
In *data import* section, mention that also these functions from mia package are available to import data from different formats. No example needed, just the name:
- makeTreeSummarizedExperimentFromDADA2, makeSummarizedExperimentFromBiom
- loadFromMetaphlan
- readQZA

In the same chapter where MDS / PCoA examples are given, also mention that the following are available (I will then modify further). Also add the full name there (JSD = Jensen-Shannon divergence etc.). The names can be found from the function manpages. No examples needed to OMA for these.
- calculateJSD, runJSD
- calculateNMDS, plotNMDS
- calculateCCA, runCCA
- calculateRDA, runRDA
- calculateOverlap, runOverlap
- calculateDPCoA, runDPCoA

In the data manipulation chapter, mention that data can be rarified with:
- subsampleCounts (rarification) -> section on "Library size"!
- also add a citation to this paper (see the function manpage for 1-2 sentences of explanation,I think it already cites this paper): https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003531

Section on Quality Control, mention:
- isContaminant, isNotContaminant
- addContaminantQC, addNotContaminantQC

Just mention these as well, with at most 1 sentence description:
- mapTaxonomy -> section on Tidying and subsetting
- getPrevalentAbundance (abundance of prevalents) -> section on Prevalence
- getRareTaxa, subsetByRareTaxa -> section on Prevalence
- mergeRows (mergeCols) -> section on Tidying and subsetting
- getUniqueTaxa -> section on Top Taxa
- bestDMNFit -> mention in Dirichlet Multinomial Mixture section
- performDMNgroupCV -> add later; mention in Dirichlet Multinomial Mixture section
- estimateDivergence -> in section on beta diversity

**Comment by RiboRings** [comment]
What if I added the links to the corresponding man pages? For instance:

# Other functions
* [makeTreeSummarizedExperimentFromDADA2](https://microbiome.github.io/mia/reference/makeTreeSummarizedExperimentFromDADA2.html)
* [loadFromMetaphlan](https://microbiome.github.io/mia/reference/loadFromMetaphlan.html)
* [readQZA](https://microbiome.github.io/mia/reference/loadFromQIIME2.html)
