### ISSUE TITLE
Unifrac example

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#123]
Good to have example on tree-aware beta diversity. Include in beta diversity chapter, same place with Bray-Curtis MDS examples:
calculateUnifrac and/or runUnifrac and visualization. Show the same Bray-Curtis/MDS(PCoA) plot also with Unifrac distances.

**Comment by RiboRings** [comment]
Hi! Unifrac has already been discussed in the [chapter on beta diversity](https://github.com/microbiome/OMA/blob/RiboRings/20_beta_diversity.Rmd) (lines 201 - 211). Should I add something anyway?

**Comment by antagomir** [comment]
No, this is ok.
