### ISSUE TITLE
LibrarySize

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#15]
Refer to these commonly used concepts in MiaBook:

- `librarySizeFactors` is available from scuttle to calculate relative library sizes
- `colSums` is the function to get absolute values (total read counts per sample)

**Comment by FelixErnst** [comment]
In addition `addPerFeatureQC` and `addPerCellQC` are available. These function attach summary data directly to the `rowData`/`colData`

**Comment by antagomir** [comment]
Some more on this can be added to subsection titled "Library size".
