### ISSUE TITLE
Associate / cross-correlate workflows

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#16]
The microbiome pkg has function [associate](https://github.com/microbiome/microbiome/blob/master/R/associate.R) to cross-correlate (or associate) taxonomic and other features for instance for [heatmap visualizations](https://microbiome.github.io/tutorials/Heatmap.html) of such associations.

Such functionality is not easily added to R packages in a sufficiently generic form and there are many different techniques in the R universe for such tasks. 

In the context of SE data, which is specifically suited for multi-omics / multi-source analyses, an easy access to a standard set of such associative techniques could be justified and facilitate exploration & visualization and example workflows will be a valuable addition to MiaBook.

**Comment by TuomasBorman** [comment]
I think this can be closed
