### ISSUE TITLE
adonis2 / PERMANOVA

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#171]
[MehrbodEstaki](https://twitter.com/MehrbodEstaki) correctly pointed out in his [tweet](https://twitter.com/MehrbodEstaki/status/1537933955248205824): "PSA: if you're using vegan's adonis for PERMANOVA test, you're doing a sequence of terms test, meaning the order of your variables matters! Luckily, adonis2 can do a marginal test, but is still not the default and has to be set with by="margin""

OMA could indeed switch to the adonis2+margin version, and have a brief note on this.

**Comment by TuomasBorman** [comment]
We can add this since this is quite imprtant to notice. Since we have only one term in our models, this do not have an effect, I think

**Comment by antagomir** [comment]
Yes no effect with a single variable. But note and recommended method is important.
