### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by TuomasBorman** [microbiome/OMA#174]
https://microbiome.github.io/OMA/community-similarity.html#other-ordination-methods

rda --> runRDA

**Comment by TuomasBorman** [comment]
maybe simplify the dbrda example??

**Comment by TuomasBorman** [comment]
Remove the group variable?

If one tries to run only on example, the example data set does not have group variable. --> It is not possible to run just one examples at the end of the page

https://microbiome.github.io/OMA/community-similarity.html#explained-variance

**Comment by TuomasBorman** [comment]
https://microbiome.github.io/OMA/community-similarity.html#explained-variance 

There is used vegan functions directly. Change to miaverse functions?

**Comment by TuomasBorman** [comment]
dbRDA does not work when the variable is not binary

https://microbiome.github.io/OMA/community-similarity.html#explained-variance

**Comment by TuomasBorman** [comment]
Add interpretation to examples

for example: https://microbiome.github.io/OMA/community-similarity.html#other-ordination-methods

**Comment by TuomasBorman** [comment]
t-SNE --> UMAP

**Comment by TuomasBorman** [comment]
Remove "FIXME: let us switch to UMAP for the examples?"

**Comment by TuomasBorman** [comment]
To the section that tells about multiassay analyses add a link to mae construction

**Comment by TuomasBorman** [comment]
plotAbundanceDensity: is there an option to add sample annotations (which sample is in which group)

**Comment by TuomasBorman** [comment]
testExperimentCrossCorrelation: option for altExp?

**Comment by TuomasBorman** [comment]
Specify that they are equal with euclidean distances https://microbiome.github.io/OMA/community-similarity.html#testing-differences-in-community-composition-between-sample-groups

**Comment by TuomasBorman** [comment]
Supervised ML?

**Comment by antagomir** [comment]
Yes these are useful suggestions to improve the text.

**Comment by antagomir** [comment]
Can be closed?

**Comment by TuomasBorman** [comment]
These things are taken into account. Can be closed.
