### ISSUE TITLE
Include general introduction to Bioconductor classes

### ISSUE THREAD

**Issue by FelixErnst** [microbiome/OMA#18]
Since not everyone is familiar with the S4 classes used in Bioconductor, a detailed introduction might be in order. 

Proposed structure:
- S4 system: links to books.
- `DataFrame`: the general data structure used throughout. Similar to `data.frame`, but S4. Nesting capability. Splitability with the need for copying data in memory. Generally faster for bigger datasets, if used correctly. 
- `DNAString`/`DNAStringSet`: efficient container for handling DNA sequences. Also comes as additional flavour `RNAString`/`RNAStringSet` for RNA sequences.
- `GRanges`/`GRangesList`: container for holding genomic range information. Efficient representation of `gff`,`bed` and other similarly structured files
- `NumericList`/`IntegerList`/`CharacterList`: Efficient storage of data of the three types split into lists.
- Combination of data is easy: `DataFrame` can hold `DNAString`,`*List` or other Bioconductor datatypes in a column (even an additional `DataFrame`)

**Comment by antagomir** [comment]
Yes, it is good to have brief summary. Not too long bc this is not in the main scope of the book. But it can help to understand many choices.

**Comment by FelixErnst** [comment]
Any volunteers? This might be a good opportunity to get to know the basics. Details should be extracted from the individual man pages, but don't forget to look into the code basis as well.

@tvborm @ChouaibB @HenrikEckermann  ?

**Comment by antagomir** [comment]
Probably some intro material could be recycled from other (open) sources. I can certainly contribute to polishing text.
