### ISSUE TITLE
Consider Quarto as the basis for the final book version

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#188]
Quarto appears promising, and especially good feedback on books:
https://quarto.org/docs/gallery/

**Comment by antagomir** [comment]
This has been done with Quarto, for instance:
https://jjallaire.github.io/hopr/

**Comment by TuomasBorman** [comment]
I agree, I have been planning to start using Quarto instead of Rmarkdown in my projects. --> we could convert these Rmd files into Quarto (and start recommending Quarto (for example, one exercise was about creating Rmd file...)

There should be a command that converts automatically Rmd to Quarto if I remember correctly

**Comment by antagomir** [comment]
Yes.

And in many cases Rmd files are readily usable without changes; although it might then be informative to change the file name to `.qmd`.

There may be some issues in converting the book. For instance, the packages seem to be loaded per chapter, one has to check that the necessary packages are load per each chapter. This will probably just improve the usability of the material.

**Comment by TuomasBorman** [comment]
Also, consider using [BiocBook](https://github.com/js2264/BiocBook)

**Comment by ake123** [comment]
Here is an error 
```r
Quitting from lines 217-246 [taxa_clustering] (11_taxonomic_information.qmd)
Error:
! unused argument (dist.fun = function (x, method = "euclidean", diag = FALSE, upper = FALSE, p = 2) 
{
    if (!is.na(pmatch(method, "euclidian"))) method <- "euclidean"
    METHODS <- c("euclidean", "maximum", "manhattan", "canberra", "binary", "minkowski")
    method <- pmatch(method, METHODS)
    if (is.na(method)) stop("invalid distance method")
    if (method == -1) stop("ambiguous distance method")
    x <- as.matrix(x)
    N <- nrow(x)
    attrs <- if (method == 6) list(Size = N, Labels = dimnames(x)[[1]], Diag = diag, Upper = upper, method = METHODS[method], p = p, call = match.call(), class = "dist") else list(Size = N, Labels = dimnames(x)[[1]], Diag = diag, Upper = upper, method = METHODS[method], call = match.call(), class = "dist")
    .Call(C_Cdist, x, method, attrs, p)
})
Backtrace:
 1. mia::cluster(...)
 2. mia::cluster(...)
 4. bluster::clusterRows(mat, BLUSPARAM, full)
 5. bluster:::.cut_hierarchical(hcl, dst, BLUSPARAM)
 6. base::do.call(fun, c(list(hcl), args))

```
similar errors are coming from other qmd 


```r
Quitting from lines 119-132 [hclust2] (24_clustering.qmd)
Error:
! unused argument (metric = "bray")
Backtrace:
 1. mia::cluster(...)
 2. mia::cluster(...)
 4. bluster::clusterRows(mat, BLUSPARAM, full)
 5. base::do.call(dist, dargs)
Execution halted

```

**Comment by antagomir** [comment]
Are you able to reproduce the error otherwise, if you run the corresponding code on your laptop? Or is this something that only occurs in automated GHA builds? Have you checked that the package versions correspond to the latest ones (is the bluster using Bioc release, or Github development version here..?)

**Comment by ake123** [comment]
It seems that I have managed to fix it

**Comment by antagomir** [comment]
Can you just make a PR to OMA and we switch to that system if it works.

Also check that the rendering instructions in README are correct.

**Comment by antagomir** [comment]
Done now I guess.
