### ISSUE TITLE
transformSamples(tse, method = "relabundance")

### ISSUE THREAD

**Issue by byjediaz** [microbiome/OMA#192]
Hello, please, I was just trying this pipeline, but i keep getting the error:

Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘transformSamples’ for signature ‘"phyloseq"’

I tried using R version 4.0; 4.1 and 4.2, none seems to work. I updated all packages or keep outdated, bot nothing seems working.

Would you please have a suggestion?

**Comment by antagomir** [comment]
This function has been designed to work with microbiome data that is stored in a TreeSummarizedExperiment data object. You are trying to apply this function to phyloseq object. The mia package has a function to convert phyloseq to TreeSE: [makeTreeSEFromPhyloseq](https://microbiome.github.io/mia/reference/makeTreeSEFromPhyloseq.html)

**Comment by byjediaz** [comment]
> This function has been designed to work with microbiome data that is stored in a TreeSummarizedExperiment data object. You are trying to apply this function to phyloseq object. The mia package has a function to convert phyloseq to TreeSE: [makeTreeSEFromPhyloseq](https://microbiome.github.io/mia/reference/makeTreeSEFromPhyloseq.html)

Thank you very much, it worked perfectly!

**Comment by antagomir** [comment]
FOr more, see microbiome.github.io/OMA :-)

**Comment by byjediaz** [comment]
> FOr more, see microbiome.github.io/OMA :-)

Yes, thank you, I found the information in the first part of the book. But, I have another doubt, as i have a phyloseq object, I tried to convert this to a TSE object but, the taxonomic information  was lost, instead of taxonomic taxa names i got ASV 01, 02, etc.

**Comment by antagomir** [comment]
Hmm could you open a new issue in the [mia package issues](https://github.com/microbiome/mia/issues) and provide a reproducible example?
