### ISSUE TITLE
Wrong "Tree-based methods" example

### ISSUE THREAD

**Issue by ChouaibB** [microbiome/OMA#196]
Hi,

I have made this examples https://microbiome.github.io/OMA/differential-abundance.html#tree-based-methods a long ago, which was supposed to use phylogeny tree information at the method. However, none was used in the example, as well as the method does not seem to accept/incorporate phylo tree in the analysis.

Shall the method be changed for instance to [MiRKAT](https://pubmed.ncbi.nlm.nih.gov/25957468/)? (here is also an example at [vignette](https://cran.r-project.org/web/packages/MiRKAT/vignettes/MiRKAT_Vignette.html)). Or some other method?

Thanks,

Chouaib

**Comment by TuomasBorman** [comment]
Hi,

yes, it should be changed since tree is not used. We could move this fido example to extra material

I don't have experience on this MiRKAT; maybe Leo has suggestion

**Comment by antagomir** [comment]
I suggest to move it to extra material for now to avoid confusion, while keeping this issue open. We will need to consider carefully on which methods examples development efforts are directed and what role mirkat plays on that. Aiming to revise the overall plan after the academic fall.
