### ISSUE TITLE
Switch to patchwork function for assembling multipanel plots

### ISSUE THREAD

**Issue by FelixErnst** [microbiome/OMA#20]
`patchwork` is panel combining package, which works with `ggplot2` output.

1. https://cran.r-project.org/web/packages/patchwork/index.html
2. https://patchwork.data-imaginist.com/

It is robust and quite easy to use, even for complicated plots.
I suggest to streamline all plot combination steps to use this package.

**Comment by antagomir** [comment]
I have good experience with this pkg so should be ok.

**Comment by antagomir** [comment]
Done.
