### ISSUE TITLE
SampleIDs as numbers

### ISSUE THREAD

**Issue by catiapacifico** [microbiome/OMA#202]
Hi,

I have used the Mia package in a company project and our sampleIDs are basically integers with 8 digits. When having a different SampleID order, this is not recognised when creating the TSE file and outputs different results. 
I have have created the same error with the GlobalPatterns data. When selecting for "Skin" samples, it gives a different number of features.

I'm attaching the input files and the code I ran to make it reproducible.

Thanks!

```
#Libraries
library(mia)
library(miaViz)
library(patchwork)
library(tidySummarizedExperiment)
library(tidyverse)
library(scater)
library(dplyr)

# data import
counts <- as.matrix(read.csv(file = "asv_table.csv", header = TRUE, sep = ",", check.names = FALSE, row.names=1))
assays <-  SimpleList(counts = counts)
tax <- read.csv(file = "features.csv", header = TRUE, sep = ",", check.names = FALSE, row.names=1)
samples_original <- read.csv(file = "samples_num.csv", header = TRUE, sep = ",", check.names = FALSE, row.names = 1)
samples_mock <- read.csv(file = "samples_2_num.csv", header = TRUE, sep = ",", check.names = FALSE, row.names = 1)

tse <- TreeSummarizedExperiment(assays = assays,
                                colData = samples_original,
                                rowData = tax)
tse

# keep only skin samples
tse <- tse[ , tse$SampleType %in% c("Skin")]

# show dimensions
dim(tse) #3 samples, 19216 features

# How many bacteria there are that are not present?
sum(rowSums(assay(tse, "counts")) == 0) #13355

# Take only those bacteria that are present
tse <- tse[rowSums(assay(tse, "counts")) > 0, ]
dim(tse) #3 samples, 5861 features


########


tse <- TreeSummarizedExperiment(assays = assays,
                                colData = samples_mock,
                                rowData = tax)
tse

# keep only skin samples
tse <- tse[ , tse$SampleType %in% c("Skin")]

# show dimensions
dim(tse) #3 samples, 19216 features

# How many bacteria there are that are not present?
sum(rowSums(assay(tse, "counts")) == 0) #13122

# Take only those bacteria that are present
tse <- tse[rowSums(assay(tse, "counts")) > 0, ]
dim(tse) #3 samples, 6094 features

```

[asv_table_num.csv](https://github.com/microbiome/OMA/files/10111910/asv_table_num.csv)
[samples_2_num.csv](https://github.com/microbiome/OMA/files/10111911/samples_2_num.csv)
[samples_num.csv](https://github.com/microbiome/OMA/files/10111912/samples_num.csv)
[samples.csv](https://github.com/microbiome/OMA/files/10111913/samples.csv)
[features.csv](https://github.com/microbiome/OMA/files/10111914/features.csv)
[asv_table.csv](https://github.com/microbiome/OMA/files/10111915/asv_table.csv)

**Comment by TuomasBorman** [comment]
Hello!

Thanks for creating this issue! I will look at it as soon as time allows

-Tuomas

**Comment by catiapacifico** [comment]
@TuomasBorman I just realised that I posted it to the wrong repository. Should I move it to microbiome/mia?

**Comment by TuomasBorman** [comment]
No problem, I can transfer this issue
