### ISSUE TITLE
SECOM / correlation patterns

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#211]
ANCOMBC package supports TreeSE and contains [new SECOM method for co-occurrences](nature.com/articles/s41467-022-32243-x). Consider adding an example.

**Comment by stefpeschel** [comment]
I've heard of SECOM but haven't used it yet. But I'd say it's definitely worth a closer look. By looking at non-linear relationships, it takes a different approach than the methods implemented in NetCoMi. On the other hand, SpiecEasi offers some features that SECOM does not, such as cross-domain network learning and the ability to learn latent variable graph models. 

In principle, one could already use SECOM with NetCoMi, if the association matrix is generated with SECOM in advance and then sent to NetCoMi.

**Comment by antagomir** [comment]
Let's at least cite SECOM in the network chapter in a suitable place?
