### ISSUE TITLE
DA tutorial, 11.1.7 Comparison of the methods - error message

### ISSUE THREAD

**Issue by mariamaseng** [microbiome/OMA#212]
Hi! Thanks for a great package! It is very useful in my research!

I am following the tutorial; https://microbiome.github.io/OMA/differential-abundance.html, and aiming to run the comparison of the different DA methods (11.1.7 Comparison of the methods) after following the code above. However, it gives me the error message; 
  
error in evaluating the argument 'x' in selecting a method for function 'full_join': error in evaluating the argument 'x' in selecting a method for function 'full_join': Input includes an object that is not 'SummarizedExperiment'.

Any idea of what may cause it?

Thanks, Maria

**Comment by antagomir** [comment]
Could provide a reproducible example for this error to help with the troubleshooting?

Did you check that the input object has correct type i.e. (Tree)SummarizedExperiment

**Comment by antagomir** [comment]
Perhaps the easiest option is to remove direct method comparisons from the DA chapter.

Such comparison can be included as an exercise in DA exercises Ch. 17.
