### ISSUE TITLE
Figure on TSE 

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#22]
Add [illustration of the TreeSummarizedExperiment](https://github.com/FelixErnst/TreeSummarizedExperiment/blob/2293440c6e70ae4d6e978b6fdf2c42fdea7fb36a/vignettes/tse2.png) data structure at the [data section](https://microbiome.github.io/OMA/data-introduction.html#loading-experimental-microbiome-data) with an appropriate citation to [F1000](https://f1000research.com/articles/9-1246) AND the later extension with the sequence slot in [EuroBioc](https://f1000research.com/slides/9-1464).

**Comment by tvborm** [comment]
Solved
