### ISSUE TITLE
Differential abundance analysis

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#24]
We could copy [course examples](https://microbiome.github.io/course_2021_radboud/differential-abundance-analysis.html) on DA analysis to the book, as the book is entirely missing this material currently. The data set could be changed to one of our demonstration data sets from [microbiomeDataSets](https://bioconductor.org/packages/devel/data/experiment/html/microbiomeDataSets.html).

**Comment by antagomir** [comment]
In addition to adding the DA examples, include also some background, and references to other relevant methods/packages and reviews. I will contribute to polishing up everything later.

- DESEq2
- ANCOMBC
- Aldex2
- lefser
-  etc

**Comment by antagomir** [comment]
Make PR and request review.

**Comment by antagomir** [comment]
@HenrikEckermann can we close this?

**Comment by HenrikEckermann** [comment]
yes
