### ISSUE TITLE
Clustering section 

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#254]
The community typing section includes now:

- hierarchical clustering
- K-means
- DMM
- link to further examples

In microbiome context, the clustering methosd DMM and CST are generally used in publications. The hclust and K-means are not specific to microbiome data and in general not recommended over DMM / CST (although exceptions may be possible). 

I would propose to 
- move demonstrations on hclust and K-means to the futher example supplementary document in the end of the section, and 
- add examples on CST (see e.g. DiGiulio et al. 2015) which may already be in the supplement document

**Comment by ake123** [comment]
Does this mean moving those sections to Appendix or to the same place and create supplementary section

**Comment by antagomir** [comment]
There is section "10.7 Additional Community Typing". Was referring to that.

**Comment by antagomir** [comment]
Note: the hclust examples for taxa are good to keep. 

Wait for PR #295 complete before changes.

**Comment by ake123** [comment]
sure!

**Comment by BananaCancer** [comment]
FYI, #295 has now been merged!

**Comment by antagomir** [comment]
Check & close this if all is ready? @ake123
