### ISSUE TITLE
ML workflow issue

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#263]
When I try to run manually from the file 40_machine_learning.Rmd I get the following error

``` 
results <- run_ml(df, "rf", outcome_colname = "diet", 
                  kfold = 2, cv_times = 5, training_frac = 0.8)
``` 

Using 'diet' as the outcome column.
Training the model...
Error in { : task 1 failed - "unused argument (type = "prob")"
In addition: There were 30 warnings (use warnings() to see them)

**Comment by erawijantari** [comment]
I cannot reproduce the error. 
I run through the commands line and Rstudio, both work fine.

**Comment by antagomir** [comment]
Works now. Temporary error.
