### ISSUE TITLE
Triplot examples for (db)RDA

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#268]
RDA plots can indicate both features as well as covariates that influence ordination. Would be good to show examples in OMA, too. 

Here some examples:
https://stackoverflow.com/questions/32194193/plotting-rda-vegan-in-ggplot

Here some discussion on extracting feature scores:
https://github.com/vegandevs/vegan/issues/254

**Comment by antagomir** [comment]
The microViz package contains also nice RDA plot examples. The license is GPL-3 though (hence not directly compatible source code).

**Comment by antagomir** [comment]
Also check #36

**Comment by antagomir** [comment]
@RiboRings this seems related to https://github.com/microbiome/mia/issues/541

**Comment by antagomir** [comment]
@RiboRings is this something we could close?

**Comment by RiboRings** [comment]
Hi! I have no material for this issue right now. If urgent it could be reassigned.

**Comment by antagomir** [comment]
I think we can close this for now but good to have it on record.
