### ISSUE TITLE
Example on network analysis

### ISSUE THREAD

**Issue by stefpeschel** [microbiome/OMA#269]
Hi! 
As Christian Müller (@muellsen) already wrote via email, we would love to contribute to the book with a part on network learning and analysis using the [NetCoMi](https://github.com/stefpeschel/NetCoMi) package. 

I have familiarized myself with the chapters and wonder where our contribution would best fit. @antagomir suggested adding something to the Exercises chapter, but that would only make sense if a network example is also given somewhere else in the book. Or am I seeing this wrong?

In my opinion, a network analysis example could fit in the Visualization chapter. We would then use the data set used in that chapter to demonstrate our proposed workflow for network construction and analysis. I.e., we would construct a microbe-microbe association network using an appropriate method and show a network plot with node colors and shapes used to highlight certain features. For the many different methods for learning the network (association estimation, model selection, ...) we could simply refer to our paper and GitHub page. What do you think?

Best,
Steffi

**Comment by antagomir** [comment]
Thanks!

How about adding a dedicated network analysis chapter? Given the importance and broad interest of this topic it would be well justified. And when the material is in it will always be possible to adjust a bit.

Exercises indeed make sense as suggested extra material for training purposes.

**Comment by stefpeschel** [comment]
Great. We'd love to do that! An own chapter on network analysis would be perfect.

**Comment by antagomir** [comment]
Looking fwd!

**Comment by antagomir** [comment]
@TuomasBorman this can be closed as we have the chapters now, I think. So I am closing. Reopen if I was mistaken.
