### ISSUE TITLE
Complete workflow examples?

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#274]
This was feedback from a course. Good idea. 

Another option is to publish workflows as separate worfklow publications (e.g. F1000 Bioc pathway) and link to them from OMA.

OSCA has separate [sub-book on workflows](https://bioconductor.org/books/release/OSCA/book-contents.html#introduction)

**Comment by antagomir** [comment]
Exercise for students to create such?

**Comment by antagomir** [comment]
@jepasan we could check this to get fwd with the reproducible summary documents, first using public example data from here (so no need to ask from FBR yet)?

We could use, for instance, data from Grieneisen et al. , see also #88

**Comment by jepasan** [comment]
@antagomir Sounds reasonable enough, I'll start working on this when I have the chance.

**Comment by antagomir** [comment]
Now we have some workflows. When OMA & mia gets more ready otherwise, we could make a call for workflow examples contributed by the community.
