### ISSUE TITLE
assay.type argument

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#293]
OMA still has examples with exprs_values and assay_name arguments that are now deprecated and replaced with assay.type 

-> this should be changed across the entire OMA.

**Comment by himmil** [comment]
Function ancombc2 does not accept assay.type argument but only assay_name.

**Comment by antagomir** [comment]
Does this also hold with the latest development version of ancombc2?

If yes, then ancombc should be updated since assay.type is now the argument name.

Ideally this argument would be passed to mia/TreeSE functions via `...` if there is no reason to do additional processing in ancombc2 itself. This would remove maintenance burden from ancomb2.

**Comment by antagomir** [comment]
Is this already dealt with?

**Comment by antagomir** [comment]
I think @Daenarys8 is now working on a new PR for ANCOMBC on this.

**Comment by antagomir** [comment]
@Daenarys8 is this one ready?

**Comment by Daenarys8** [comment]
not yet. will push by todays end

**Comment by antagomir** [comment]
Great!
