### ISSUE TITLE
Add solutions to training exercises as foldable code chunks

### ISSUE THREAD

**Issue by RiboRings** [microbiome/OMA#297]
The [Exercise chapter](https://microbiome.github.io/OMA/exercises.html) has plenty of exercises. Let's add solutions to them as
foldable code chunks, closed by default and opened when user clicks on them.

It can be done with:

```
output:
  html_document:
    code_folding: hide
```

**Comment by antagomir** [comment]
When there is time we have received regular requests to add solutions for the exercises.. would be nice to see some community contributions here.. :-)

**Comment by RiboRings** [comment]
https://github.com/microbiome/OMA/pull/390

**Comment by antagomir** [comment]
Giulio - could you check if this is easy to add in the new version of the book?

**Comment by antagomir** [comment]
If not easy then let's rethink.

**Comment by RiboRings** [comment]
Hi! In theory, this should be working in the current version of the book. However, the folded code doesn't appear in the chapter. Not sure yet what the problem is.

**Comment by RiboRings** [comment]
The reason could be that code folding is only supported by executed code chunks: https://quarto.org/docs/output-formats/html-code.html

Maybe we could run the code in the examples, or if that takes too long we could comment out all the lines of the example chunks and "execute" it.

**Comment by antagomir** [comment]
hmm perhaps we could first add this to some light-weight cases where it is simple; for more heavy examples there could be a link to an external file (in OMA repo but not included in the book)?

**Comment by RiboRings** [comment]
For some reason, the folded chunks appear locally, but they are not rendered in the online version of the book. Below is a picture of what is looks like when rendered locally:

![Screenshot 2024-04-17 at 10 52 02](https://github.com/microbiome/OMA/assets/82203661/9d7340ec-ef1c-4cac-9fb0-bedca1dde2d5)

**Comment by RiboRings** [comment]
Some possible actions:
- test if chunk appears in the online book when setting `EVAL = TRUE` (also precede all lines with `#` so they don't execute
- understand why code folding works only locally, and try to fix it in the online book

**Comment by ake123** [comment]
```
::: {.callout-SOLUTION1 collapse="true"}
```{r}
```
:::
```

**Comment by RiboRings** [comment]
Thank you @ake123 

Then in principle if someone is willing, they can add solutions to selected exercises in preparation for summer schools and courses as shown in [the comment above](https://github.com/microbiome/OMA/issues/297#issuecomment-1936052614).

**Comment by ake123** [comment]
I am willing to add solutions I need to know which ones. I can actually do all if needed

**Comment by RiboRings** [comment]
That would be super useful!

@antagomir  mentioned that we might need to consider whether it makes sense to add solutions to all exercises, or if it is only necessary for the more complex exercises, and the easier exercises would just contain a link to the corresponding OMA chapter (also to avoid redundant code).

How should we proceed?

**Comment by antagomir** [comment]
Ok @ake123 if you could do the following for  the material in chapter 18.3? https://microbiome.github.io/OMA/docs/devel/pages/98_exercises.html

1) Go through those exercises, and verify that they are clear and work well. Improve the exercise text or tips where necessary.

2) Add citation to the relevant OMA chapters / function names as a tip; also the tips can be folded

3) provide brief (folded) example solutions for those exercises where it seems useful; if the solution is obvious from the material that is already provided in the proper chapters, then see if it is enough to just cite the relevant chapter. We don't want to duplicate all material from the book to the exercises as this doesn't make sense.

4) Where possible, avoid referring to specific data sets in the exercise text; the solution needs to operate on concrete data however.

Let's see how this works for chapter 18.3, then we can see how to do with the other chapters.

**Comment by ake123** [comment]
Solutions are ready!

**Comment by antagomir** [comment]
@jkc9886 could you check if the exercise chapter contains tasks for which you could propose solutions (as a PR)?

**Comment by antagomir** [comment]
Foldable chunks seems to work now. It seems we can close this.
