### ISSUE TITLE
Prefer Features over Taxa in the examples

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#302]
We have many functions that refer to "Taxa" in their name, for instance (but not limited to): `getTopTaxa, getDominantTaxa, subsetByRareTaxa, subsetByPrevalentTaxa, addPerSampleDominantTaxa` etc.

This may become a limitation in the longer term since the rows could also correspond to genes, functional features etc. and in fact there is nothing taxa-specific in these functions. Therefore I would suggest to promote the use of a more generic name.

We have another name (alias) for all or most of these functions, where "Taxa" is replaced by "Features". 

I suggest the following:

1. only use the "Features" function name throughout OMA (replace "Taxa" with "Features" for these function calls)
2. consider deprecating the "Taxa" function names in mia pkg family in those (all?) cases where the function is not having anything really specific to taxa. A new issue (and subsequent PR) for that should be opened in the respective packages (mia, miaViz, miaTime, miaSim). Changes are probably rather minimal in other packages than mia. This will support longer term compatibility across the ecosystem of other tools.

**Comment by antagomir** [comment]
@TuomasBorman comments welcome and I suggest that @himmil would implement it based on this.

**Comment by TuomasBorman** [comment]
1. OK
2. OK. Indeed, it would bring mia packages closer to other part of SE ecosystem and might enhance bidirectional utilization of tools (we have also some tools that might be beneficial for others)

**Comment by antagomir** [comment]
Based on our subsequent discussion in Slack, I gather the following points and suggestions.

1. Functions that do not have specific difference in rows vs. columns could be named generically; instead of clusterRows/clusterCols one can have just "cluster" and margin argument (done); for mergeRows/mergeCols it would just "merge"; check if there are other similar functions. At the same go the "merge" function could be renamed as "collapse" (or something else) to differentiate it from merge commands that merge full data.frames or SE objects (instead of rows)
2. In general, unify the terms taxa/features/rows and samples/cols in the function names. In general, use features/samples rather than rows/cols in the cases where it is relevant that the function concerns features or samples specifically. When it is not relevant, drop these terms entirely and just provide the margin argument for the function (e.g. "cluster", "merge" etc.). This should be done through deprecation (old names should remain functional for some time).
3. Abandon "taxa" in the function names entirely (replace with "features").

**Comment by antagomir** [comment]
It is possible to split this issue in multiple, smaller issues, to be handled one-by-one. This is not an urgent issue but would be useful.

**Comment by antagomir** [comment]
The DataFrame class uses "combine" for row/col merging:

>  DataFrame-combine for ‘combineRows()’, ‘combineCols()’, and
>           ‘combineUniqueCols()’ examples involving DataFrame objects.

-> This is one option for naming.

**Comment by antagomir** [comment]
Ok let us implement the following in this

Change all OMA examples so that they use the "Features" ending instead of  "Taxa" ending for these function calls (both versions of the names are already available so this will be simple string replacement that can be on command line e.g with _sed_):

- getTopTaxa
- getDominantTaxa
- subsetByRareTaxa
- subsetByPrevalentTaxa
- addPerSampleDominantTaxa


Check if there are other functions in mia/OMA with the "Taxa" ending. Probably those should be updated similarly.




**As a separate PR (can be ignore here now), I also opened issues in mia:**

Regarding mergeRows/mergeCols:
https://github.com/microbiome/mia/issues/391

Regarding Taxa -> Features renaming and deprecation:
https://github.com/microbiome/mia/issues/392
https://github.com/microbiome/mia/issues/393

**Comment by antagomir** [comment]
@himmil could you take care of the renaming?
