### ISSUE TITLE
Make instructions on data import clear and consistent

### ISSUE THREAD

**Issue by RiboRings** [microbiome/OMA#307]
The information about constructing TreeSE / MAE from raw files is inconsistent or misleading. Things to do:

1. Revise and update instructions on import and construction in [this chapter](https://microbiome.github.io/OMA/containers.html#loading-experimental-microbiome-data) (for example, `loadFromBiom` should be replaced with `makeTreeSEfromBiom`)
2. Move raw files from Julia package, course repos etc. to the [microbiome data repo](https://github.com/microbiome/data) and make it accessible from OMA with links
3. Update links in [this exercise](https://microbiome.github.io/OMA/exercises.html#construct-TreeSE) and [this exercise](https://microbiome.github.io/OMA/exercises.html#mae-reconstruction) so they point to raw files in [microbiome data repo](https://github.com/microbiome/data) instead of the Julia package
4. Make [this exercise](https://microbiome.github.io/OMA/exercises.html#importing-data) consistent with instructions on import and construction given in [this chapter](https://microbiome.github.io/OMA/containers.html#loading-experimental-microbiome-data)

**Comment by antagomir** [comment]
Also see
https://github.com/microbiome/mia/pull/406

-> @ChouaibB working on some simplifications related to function implementation.
