### ISSUE TITLE
plotColData from scater

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#329]
The exercises in 17.5 and perhaps also other parts in OMA could indicate more clearly from which package functions come from, e.g. plotColData is scater::plotColData

**Comment by antagomir** [comment]
To NdG?

**Comment by antagomir** [comment]
Close when ready

**Comment by antagomir** [comment]
@jkc9886 can you check if this is OK now and close the issue when ready?

**Comment by jkc9886** [comment]
Sure, I shall work on that

**Comment by antagomir** [comment]
up @jkc9886 ?

**Comment by jkc9886** [comment]
If I understood it correct, do you intend that all mention of functions in OMA has the package indication with it?

**Comment by antagomir** [comment]
Hmm yes.. with a second thought, that might be a bit much. We can do this case-by-case.
