### ISSUE TITLE
Interoperability with Jl/Py

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#330]
Show how to export TreeSE/MAE data such that it can be reused in Julia (or Python). 

The feather file format could do for this. 

Julia already has SE & MAE implemented.

This can support longer term developments.

**Comment by antagomir** [comment]
@ElySeraidarian you have self-assigned this - any chance to check it through?

**Comment by antagomir** [comment]
Or can we just close this issue already since the issue has been merged?

**Comment by ElySeraidarian** [comment]
The section created in the OMA book explains how to export TSE/MAE in Julia and Python so I think we can close this
