### ISSUE TITLE
Rarefaction as optional strategy for beta diversity

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#332]
Ref: Pat Schloss' [recent analyses](https://www.biorxiv.org/content/10.1101/2023.06.23.546313v1.full.pdf) on rarefaction in alpha & beta diversity. This addressess well some of the long debates and controversies surrounding rarefaction in microbial ecology.

Based on this I tend to think that rarefaction should be provided as an option for beta diversity calculations.

Here rarefaction refers to averaging alpha diversity estimates across many random rarifications (100x and 1000x are used in the preprint). This makes most difference in less diverse and low abundance environments but may influence also more rich ecosystems (see the preprint).

In that prepint: ""Beta-diversity values generated with rarefaction were calculated using the avgdist function in vegan.
Briefly, vegan’s avgdist function calculates each pairwise dissimilarity index after obtaining a random
draw of the same number of sequences from each sample. After obtaining 100 random draws it returns
the mean value.""

We might be able to use this directly with scater::runMDS via the FUN argument from the latest PRs contributed by @BananaCancer - worth checking.

Then this could be provided as a recommended option in OMA.

Not sure if this can be addressed in reasonable new ways in mia, given that the beta diversity functionality largely comes from vegan and scater packages.

**Comment by antagomir** [comment]
See also https://github.com/microbiome/mia/issues/463

**Comment by antagomir** [comment]
@thpralas would you be interested looking into this once the situation relaxes? (assuming that @RiboRings is not already working on this - I guess he stays busy with other related topics). This is a good, more extensive task to look at and discuss, then providing a suitable solution in mia & OMA.

**Comment by theotimeee** [comment]
> @thpralas would you be interested looking into this once the situation relaxes? (assuming that @RiboRings is not already working on this - I guess he stays busy with other related topics). This is a good, more extensive task to look at and discuss, then providing a suitable solution in mia & OMA.

Thanks! I will look into this soon.

**Comment by antagomir** [comment]
@thpralas also close this when the PR gets ready?

**Comment by antagomir** [comment]
@thpralas is this something we can close now?

**Comment by antagomir** [comment]
Seems ready.
