### ISSUE TITLE
Clustering chapter

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#337]
Clustering chapter represents many methods that not usually applied in microbiome context. 

Move K-means and graph-based clustering to supplementary materials (not shown in TOC but can be available behind a link; see Section 10.7 on "Additional community typing").

Also other polishing needed for instance this generates unnecessarily long output that makes the page difficult to read and browse:
```
# Check the result contained in the clusters part of colData
colData(tse)$clusters
```

-> check and polish the overall style a bit

We would like to demonstrate how to do Community State Typing (CST), can be discussed after first polishing the current chapter.

**Comment by TuomasBorman** [comment]
Also, in https://microbiome.github.io/OMA/clustering.html#dirichlet-multinomial-mixtures-dmm DMM is stored into new object. It should be stored to tse variable.
