### ISSUE TITLE
ggsignif

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#340]
For examples with boxplots representing significance, the ggsnignif pkg is now supporting multiple testing correction:
https://github.com/const-ae/ggsignif/issues/28#issuecomment-1704469175 -> add an example how to use this common functionality?

**Comment by antagomir** [comment]
There is the new argument "correction" for geom_signif (see https://github.com/elnaggarj/ggsignif-FDR/blob/main/R/geom_signif.R).

We have existing example of this one in Ch. 6 in OMA
https://microbiome.github.io/OMA/docs/devel/pages/14_alpha_diversity.html

-> Update the example to include multiple testing correction.

**Comment by TuomasBorman** [comment]
I found out that this is incorrect solution. correction parameter is in ggsignif-FDR  package which is fork of ggsignif. The issue still exists, and our solution gives wrong answer.

**Comment by TuomasBorman** [comment]
I am restructuring the book before having some holiday. I will hopefully be ready in couple of days with my PR. I will take this thing also into account.
