### ISSUE TITLE
Add phyloseq vs TreeSE cheatsheet

### ISSUE THREAD

**Issue by TuomasBorman** [microbiome/OMA#354]
To help users to convert phyloseq workflows to TreeSE, add info on equivalences (tax_table vs rowData, otu_table vs assays...)

Maybe in picture format...

**Comment by antagomir** [comment]
Under construction in #358 #397

**Comment by antagomir** [comment]
Can be closed? @ake123

**Comment by ake123** [comment]
Yes it can closed!

**Comment by antagomir** [comment]
close if ok
