### ISSUE TITLE
Add new data resource

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#355]
Add link and explanation of [Microbiome Compendium](https://github.com/seandavi/MicroBioMap#microbiome-compendium) in OMA.

**Comment by antagomir** [comment]
* Dataset https://t.co/VopPEah8y3
* R package: https://t.co/CUmc3AgY6f
* Website: https://t.co/XbKGLNdmeN
* Preprint! https://t.co/eLFFYCFWc7

**Comment by Daenarys8** [comment]
let me claim this:)

**Comment by antagomir** [comment]
Sure, please assign yourself?

**Comment by antagomir** [comment]
This seems to be in 2.3.4. @Daenarys8 is this ready (close?)

**Comment by 0xMuluh** [comment]
ahh yes. this was merged already.
