### ISSUE TITLE
addTaxonomyTree

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#364]
The addTaxonomyTree creates rowTree based on taxonomic rank hierarchy. This is different from the actual phylogenetic tree and may cause confusion.

I suggest to remove addTaxonomyTree from examples entirely, or have it only in a single place where it is explained together with the actual phylogenetic tree (which is included in some of the demo data sets, like Tengeler2020), and their difference must be explained.

**Comment by antagomir** [comment]
@thpralas is this ready?

**Comment by theotimeee** [comment]
> @thpralas is this ready?

Yes but I am not sure if the example about Tengeler2020 is clear enough. Although its tree is described as a phylogenetic tree, this description is also printed for hierarchy trees that are not actual phylogenetic trees. The difference is explained above the example but it might still be confusing I think

**Comment by antagomir** [comment]
Is this now OK and can be closed @thpralas @TuomasBorman

**Comment by TuomasBorman** [comment]
This is ok now
