### ISSUE TITLE
Make the exercises independent of particular data

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#365]
Many of the exercises suggest to use a particular demo data set.

It would be better for training purposes to remove references to specific data sets as much as possible (there may be exceptions).

Then each trainer can use any (TreeSE) data of their choice, and point to relevant exercises that could be done with that data.

**Comment by Elina297** [comment]
I can't see how to do that because in my mind if we remove the references then there will not be the graphs and results in the book. And there are a lot of chapters where it seems important to let the dataset (it is possible but then it means that I will also have to change the text and other lines of code that are dependent of the dataset).

**Comment by antagomir** [comment]
Good point.

But I was referring to Ch. 17, which does not have graphs nor results because those are for students to generate.

The Ch. 17 exercises suggest tasks. In many cases the task mentions a specific demo data set. But also in most cases, the exercise can be done with almost any demo data set, they are not depending on particular data set as long as the data is in TreeSE format. In these cases it would make the examples more general if we will not refer to specific data sets like Tengeler2020, peerj13075 etc. in Ch 17.

**Comment by antagomir** [comment]
For instance:

> 17.3.5 Sample information
> Import the mia package, load peerj13075 with data and store it into a variable named tse.
> Check the names of the samples with colnames.
> List the information on samples available in colData with names.
> Visualize the colData with View and briefly look at the information stored in the different columns.
> Get the abundances of all features for a specific sample, such as ID34, for an assay of your choice.
> 

-> This could ask to "load one of the example data sets mentioned in Chapter XXX and rename it to tse. Then, for this tse, do the following..."

**Comment by antagomir** [comment]
I mean Chapter 17 only.

For instance:

> 17.3.5 Sample information
> Import the mia package, load peerj13075 with data and store it into a variable named tse.
> Check the names of the samples with colnames.
> List the information on samples available in colData with names.
> Visualize the colData with View and briefly look at the information stored in the different columns.
> Get the abundances of all features for a specific sample, such as ID34, for an assay of your choice.


This could be like: "Load one (any) of the data sets mentioned in Chapter XXX. Rename that data set to tse. Then do the following..."

**Comment by Elina297** [comment]
I didn't change when it was for enterotype data set cause it seems that it works well only with this one. Same for HintikkaDOData as it is the only MAE. But let me know if I have to change those ones too.

**Comment by antagomir** [comment]
Yess, sounds good. Can you open the PR so we can see it?

**Comment by Elina297** [comment]
I already made 2 PR here. I created a branch and it says that it should automatically link PR. But yes apparently it didn't work I don't know why so I don't know how to fix it... I'll check it later

**Comment by antagomir** [comment]
Have you cloned or forked this repository microbiome/OMA? Is the branch in the clone, or in the fork?

**Comment by Elina297** [comment]
The branch is in the original repository and not in my fork... That's strange because I did the same as usual, and I even did exactly the same just after for the description_file branch and this one is in my fork...

**Comment by Elina297** [comment]
Oh no ok. I created the branch 365_independy_exercises from the github page of the issue and not from git bash, that's maybe why it is in the microbiome/OMA ?

**Comment by antagomir** [comment]
I guess you can create it like that but then you have to pull that branch from OMA.. I am not sure if you are working in OMA clone or fork. If you know how to update with OMA upstream/master and then create your local branch and open PR thats ok.

**Comment by Elina297** [comment]
I'm working in the clone. I was speaking about the fork just because when I create a branch and pull request from the clone then I can see it in the fork. 
In this case I created the branch from the github page of the issue and then moved in this branch from my clone and did the PRs. 
Is there a way to put this branch in the right place or should I create a new one ?

**Comment by antagomir** [comment]
Probably there is a way but it might be more straightfwd to create a new one and copy your updates there.
