### ISSUE TITLE
Add data examples on multiAssayExperiment

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#38]
We do not have clear examples yet, where `multiAssayExperiment` would be preferred and useful over `altExp`.

**Comment by microsud** [comment]
An example multi assay is there in HMP2Data pkg in BioC. It has 16S and cytokine data. This can be used in OMA book as example?
https://github.com/dozmorovlab/HMP2Data/blob/master/vignettes/hmp2data.Rmd

**Comment by antagomir** [comment]
Yes, good. Linked to #26 as the curatedMetagenomicData has also many data sets available in TreeSE format (in part, same maintainers). 

I can have a look at this when going through OMA more systematically.

**Comment by microsud** [comment]
Yes curatedMD is only wgs metagenomics data and no multi-omics.

**Comment by antagomir** [comment]
We have now `MAE` examples in **microbiomeDataSets**
