### ISSUE TITLE
source("https://raw.githubusercontent.com/microbiome/OMA/master/install_packages.R") 

### ISSUE THREAD

**Issue by AMahajna** [microbiome/OMA#383]
**Describe the bug**

**To Reproduce**
A clear and concise description of how to reproduce the behavior.

**Expected behavior**

**Additional context**

**Comment by AMahajna** [comment]
This command doesn't work. Maybe there is misorganization?

**Comment by TuomasBorman** [comment]
Hello!

Ahhh, the file has been removed while we were polishing the directory... OMA undergo heavy maintenance during Spring; we are polishing it for Bioc submission. As a quick fix, you can find the file from older commit. 

`source("https://raw.githubusercontent.com/microbiome/OMA/8e27ea9b19d411542374869e210e3a9f92e54f53/install_packages.R")`

-Tuomas

**Comment by antagomir** [comment]
@himmil if you could check this with Noah?

**Comment by antagomir** [comment]
This is somewhat urgent, needed for training. @ake123 could you check?
