### ISSUE TITLE
pseudocount = 1 in clr assay transformation in chapter 5.4

### ISSUE THREAD

**Issue by artur-sannikov** [microbiome/OMA#391]
[Chapter 5.4](https://microbiome.github.io/OMA/docs/devel/pages/11_taxonomic_information.html#sec-assay-transform) adds 1 as pseudocount to `relabundance` assay before performing clr transformation.

```R
tse <- transformAssay(x = tse, assay.type = "relabundance", method = "clr", 
                      pseudocount = 1, name = "clr")
```

Does it make sense though? @antagomir in our discussion correctly said that adding 1 to relative abundance does not make much sense because 1 is the largest number a `relabundance` assay can have. So, the correct code should be just `pseudocount=TRUE`.

**Comment by antagomir** [comment]
It does not make sense, the correct code should be `pseudocount=TRUE`. 

Could you fix by PR?
