### ISSUE TITLE
Non-development book version

### ISSUE THREAD

**Issue by HollyRoach** [microbiome/OMA#398]
Hi, I was using a previous version of the OMA online book (https://microbiome.github.io/OMA) however this link now re-directs me to the beta version that is undergoing development. Is it possible to still access a non-development version of this book?

**Comment by TuomasBorman** [comment]
Hello!

The "old" version of OMA was also beta version. We have not yet had "published", stable version of OMA, but we are planning to finalize it during this year.

Compared to previous version, only the layout has changed. The layout change was related to bigger modifications (changing from Bookdown to BiocBook). The layout is not probably as clear as it was, and we are also planning to improve it for the stable version.

-Tuomas

**Comment by antagomir** [comment]
Yes, all versions so far have been development versions. We just changed the layout. The content is more or less the same.

**Comment by HollyRoach** [comment]
Ok great - that is good to know! Thank you for clearing this up.
