### ISSUE TITLE
BiocBook rendering

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#406]
When running  `BiocBook::preview(BiocBook::BiocBook('.'))`

I get the following:

> ✖ Some dependencies found in book pages are not listed in DESCRIPTION: 
>   • BiocManager
>   • stats
>   • reshape2
>   • devtools
>   • NetCoMi
>   • SpiecEasi
>   • SPRING
>   • RColorBrewer
>   • factoextra
>   • grid
>   • cluster
>   • dada2
> Consider adding these dependencies to DESCRIPTION
> 

-> Shall we add these in DESCRIPTION?

**Comment by TuomasBorman** [comment]
Yes, that should be done before we submit the book to Bioc
