### ISSUE TITLE
Broken citation in Chapter 11

### ISSUE THREAD

**Issue by artur-sannikov** [microbiome/OMA#425]
Citation `network-comparison` does not exist in [Chapter 11]([network-comparison?](https://microbiome.github.io/OMA/docs/devel/pages/60_network_learning.html#ref-network-comparison)).

Relevant code [here](https://github.com/microbiome/OMA/blob/master/inst/pages/60_network_learning.qmd#L12C1-L12C282).

**Comment by antagomir** [comment]
Could you make PR to fix?

**Comment by artur-sannikov** [comment]
Sure, what's the reference?

**Comment by antagomir** [comment]
Ah right - does @js2264 know and perhaps fix?
