### ISSUE TITLE
Overlapping content

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#431]
It seems we have overlapping content on adonis/dbrda calculations in sections 7.3.1 and 7.2. The former uses vegan and base R, the latter uses mia & runRDA. I suggest to unify so that the material relies extensively on (Tree)SE. 

Extra material or alternative solutions validating/replicating the approach with base R/vegan can have educational value and could be put in extra supplementary script file that is not part of OMA TOC but could live in the same github folder and linked from the text?

**Comment by antagomir** [comment]
@himmil is this ready?

**Comment by himmil** [comment]
Apparently it wasn't, sorry about this. I did not find anymore much to change

**Comment by antagomir** [comment]
All good - if the PR solves this can you also close the issue once the build pass.
