### ISSUE TITLE
Cheatsheet

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#449]
We have now phyloseq/TreeSE cheatsheet in Appendix A.5 https://microbiome.github.io/OMA/docs/devel/pages/97_extra_materials.html

1) Tidy it up (hide verbose routine rendering messages)
2) Add link to cheatsheet in section 19.1.3.2 Resources on phyloseq
3) Consider making a proper cheatsheet like this https://github.com/rOpenGov/eurostat/blob/master/inst/extras/cheatsheet/cheatsheet2019.pdf (I think there might be an R package for making cheat sheets..)

**Comment by antagomir** [comment]
At least points 1-2. 

@ElySeraidarian could you check this one?

**Comment by ElySeraidarian** [comment]
I am currently trying (just have some issues as I had the wrong R version -> downloaded the one that went out today)

**Comment by ElySeraidarian** [comment]
I made Pull Request don't know if I did everything right though

**Comment by antagomir** [comment]
Good to link here the PR number

**Comment by antagomir** [comment]
Seems to be #455

**Comment by ElySeraidarian** [comment]
PR Fixes #457
