### ISSUE TITLE
Load all packages at the beginning of the chapter

### ISSUE THREAD

**Issue by ake123** [microbiome/OMA#467]
Package import should be standardised across the book in a way that loads all packages at the beginning of the chapter.
One method is to create `load_packages.R` file and source it to the qmd files

**Comment by antagomir** [comment]
This sounds feasible to render sections.

On the other hand, from user perspective it could be helpful to see explicitly which packages need to be loaded for each analysis because often people will copypaste code to work on their own systems.

**Comment by antagomir** [comment]
@ake123 could you specify the benefits of listing the packages in the beginning of the chapter?

**Comment by antagomir** [comment]
Is this critical or can we close?

**Comment by TuomasBorman** [comment]
I think this is not critical. Also, some might think that it is better to load certain packages in chunk where they are used to higlihght the source of methods

**Comment by ake123** [comment]
Yes I agree

**Comment by antagomir** [comment]
Then let's just close it.
