### ISSUE TITLE
Standardize styles for package names, functions and object types

### ISSUE THREAD

**Issue by ake123** [microbiome/OMA#469]
Standardize package names, functions and object types throughout OMA.

one option is to use _italic_ for _R package names_, `monospaced` for `R functions (tse, assays, colData, altExp, phylo)` and simple font for object types (TreeSE, phylo, matrix)

**Comment by jkc9886** [comment]
Hello, 
Another relevant issue to #562.
I believe we have resolved this until latest? as per #584.

**Comment by antagomir** [comment]
Ok @TuomasBorman ?

**Comment by TuomasBorman** [comment]
Yes, this is now taken into account
