### ISSUE TITLE
Citation for DAA paper

### ISSUE THREAD

**Issue by TuomasBorman** [microbiome/OMA#476]
Nice paper about DAA methods https://arxiv.org/abs/2404.02691

Add citation to DAA chapter.

Also, consider adding wrapper for wilcoxon text.
1. Relatively simple to implement for users also (basically just loop)
2. Requires some coding, and widely used --> wrapper might be beneficial  (there could be option for other statistical tests)

**Comment by antagomir** [comment]
Here note that some DA methods (at least Maaslin2 I think but also others, perhaps aldex or ancombc) do include Wilcoxon test in a well polished form. It might be better to use one of the DA packages that already support TreeSE, or suggest PR adding such support to Maaslin2 for instance. Then add examples on those in OMA.

**Comment by antagomir** [comment]
Also cite the new BIRDMAn DA method?

**Comment by antagomir** [comment]
Related to #503

**Comment by TuomasBorman** [comment]
Both citations (Birdman and pelto et al) are included
