### ISSUE TITLE
Link fixing

### ISSUE THREAD

**Issue by ake123** [microbiome/OMA#479]
Some links are not working at the end of [chapter2](https://microbiome.github.io/OMA/docs/devel/pages/04_containers.html). correct those with a correct one as follows and make a PR.
[makeTreeSummarizedExperimentFromDADA2](https://microbiome.github.io/mia/reference/makeTreeSEFromDADA2.html)
[makeSummarizedExperimentFromBiom](https://microbiome.github.io/mia/reference/makeTreeSEFromBiom.html)

**Comment by antagomir** [comment]
is this ready? @ake123 @ShadmanIshraq

**Comment by ShadmanIshraq** [comment]
> is this ready? @ake123 @ShadmanIshraq

Yes, this was completed.

**Comment by antagomir** [comment]
Please close the issues as they become ready.
