### ISSUE TITLE
Duplicated `visualize-shannon` chunk

### ISSUE THREAD

**Issue by artur-sannikov** [microbiome/OMA#488]
In `14_alpha_diversity.qmd` there is a duplicated chunk `14_alpha_diversity.qmd`: [line 135 ](https://github.com/microbiome/OMA/blob/devel/inst/pages/14_alpha_diversity.qmd#L135C7-L135C24) and [line 250](https://github.com/microbiome/OMA/blob/devel/inst/pages/14_alpha_diversity.qmd#L250). Which is the correct one?

**Comment by antagomir** [comment]
I think you could just rename one. Only the name is duplicated, not the content.
