### ISSUE TITLE
Hardcoded row selection in Multi-omics Integration chapter

### ISSUE THREAD

**Issue by artur-sannikov** [microbiome/OMA#498]
Currently, the selection of rows for Intermediate Fusion algorithm is [hardcoded](https://github.com/microbiome/OMA/blob/devel/inst/pages/IntegratedLearner.qmd#L360). A better solution would be to select indices based on FeatureType.

```R
pathways_ind <- which(feature_metadata$featureType == "Pathways")
species_ind <- which(feature_metadata$featureType == "Species")

dataList[[1]] <- t(feature_table[pathways_ind, ])
dataList[[2]] <- t(feature_table[species_ind, ])
```

It's more robust to changes in the number of rows.

**Comment by TuomasBorman** [comment]
Would you be able to modify?

**Comment by antagomir** [comment]
PIng @artur-sannikov - is this something we could handle and close?

**Comment by artur-sannikov** [comment]
It was fixed on July 29. [Commit d85b18720f1f5cfef26b683e188cc21c88ed6046](https://github.com/microbiome/OMA/commit/d85b18720f1f5cfef26b683e188cc21c88ed6046). I close it now.
