### ISSUE TITLE
DA chapter

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#503]
The OMA differential abundance analysis chapter currently presents too many methods.

Remove these methods entirely from the chapter:
- LinDA
- ZicoSeq

Also otherwise check if the writing in the chapter could be developed further.

**Comment by antagomir** [comment]
@jkc9886 could you pick this one?

**Comment by jkc9886** [comment]
Yes sure. Just to confirm, by entirely you mean to remove these methods (both from tools and under DAA with confounding section) completely? I shall keep you posted about my work on the writing.

**Comment by antagomir** [comment]
@jkc9886 is this ready?

**Comment by jkc9886** [comment]
Yes, DA chapter is edited and merged :)
