### ISSUE TITLE
Rename cross-correlation analysis to cross-association analysis

### ISSUE THREAD

**Issue by artur-sannikov** [microbiome/OMA#517]
When one searches for cross-correlation, they'll see that it's mostly related to time series correlations. That can become a font of confusion for beginners.

Might "cross-association" reflect better the book's idea? Or just simply call it "correlation analysis" because cross-association is also barely mentioned in multi-omics. I found one [paper](https://pubmed.ncbi.nlm.nih.gov/36362897/).

This term is used in chapters:

1. [Community Typing (Clustering)](https://microbiome.github.io/OMA/docs/devel/pages/24_clustering.html)
2. [Multi-Assay Analyses](https://microbiome.github.io/OMA/docs/devel/pages/23_multi-assay_analyses.html)
3. [Exercises](https://microbiome.github.io/OMA/docs/devel/pages/98_exercises.html#basics-of-rbioconductor)

**Comment by TuomasBorman** [comment]
I would go with "correlation analysis". That might be something that one might try to find from google

**Comment by artur-sannikov** [comment]
Agreed. I can open a pull request if approved.

**Comment by antagomir** [comment]
@artur-sannikov what's the status of this one?

**Comment by TuomasBorman** [comment]
Note that the structure of book has changed.  Now we have chapters https://microbiome.github.io/OMA/docs/devel/pages/correlation.html and https://microbiome.github.io/OMA/docs/devel/pages/cross_correlation.html
