### ISSUE TITLE
Update the use of deprecated functions

### ISSUE THREAD

**Issue by ndegunst** [microbiome/OMA#519]
I've noticed that some functions that are still used in OMA are now deprecated, here's a short list :

- mergeFeaturesByRank should be updated to AgglomerateByRank
- testExperimentCrossCorrelation should now be getCrossAssociation() with test_significance set to True

If I find more of these I'll put them here.

**Comment by 0xMuluh** [comment]
This is now resolved.

**Comment by 0xMuluh** [comment]
Closing issue
