### ISSUE TITLE
Fix build

### ISSUE THREAD

**Issue by TuomasBorman** [microbiome/OMA#529]
This commit https://github.com/microbiome/OMA/commit/207952f25fc7283c0adb3e6141fad28865a874a6 introduced a failure of build. See the comments in the commit.

**Comment by TuomasBorman** [comment]
@jkc9886 I cannot find PR for this. Can you please fix this before creating new PRs, this is urgent

**Comment by jkc9886** [comment]
Hello, could you please check the second commit I made on June 13 in PR #518 

The final version after that commit builds well on my local system, please let me know if it still doesn't build or if I should make any changes to that :))

This link should take you there directly : https://github.com/microbiome/OMA/pull/518/commits/709943891b3f85fa3c67c73d469479b5e63a2440

**Comment by TuomasBorman** [comment]
Thanks! Sorry I did not notice it

**Comment by TuomasBorman** [comment]
This was fixed with 2653b38c11ea6887ea473a77e88b19188a7008da
