### ISSUE TITLE
Edge lines not getting connected node-to-node

### ISSUE THREAD

**Issue by Lucifer1814** [microbiome/OMA#540]
net_hv_spiceasi<-netConstruct(data = core_physeq,
                            sparsMethod = "none",
                            normMethod = "none",
                            verbose = 3,
                            measure = "spieceasi",
                            measurePar = list(method="mb",pulsar.params=list(subsample.ratio=0.9))
)

prop_hv = netAnalyze(net_hv_spiceasi,
                            centrLCC = FALSE,avDissIgnoreInf = TRUE,
                            hubPar = "degree", hubQuant = 0.95,
                            normDeg = TRUE, normBetw = TRUE, normEigen = TRUE, verbose=2, gcmHeat = FALSE)

superkingdoms <- as.character(tax_table(core_physeq)[, "superkingdom"])

# Define colors for each superkingdom
unique_superkingdoms <- unique(superkingdoms)
superkingdom_colors <- setNames(rainbow(length(unique_superkingdoms)), unique_superkingdoms)

node_names <- rownames(otu_table(core_physeq))

featVecCol <- superkingdoms
names(featVecCol) <- node_names
colorVec <- superkingdom_colors

# Now plot with node colors according to superkingdom
plot.hv_10 <- plot(prop_hv,
                   layout = "layout_with_fr",
                   layoutGroup = "union",
                   edgeFilter = "threshold",
                   edgeFilterPar = 0.1,
                   nodeColor = "feature",
                   featVecCol = featVecCol,
                   colorVec = colorVec,
                   nodeSize = "degree",
                   highlightHubs = TRUE,
                   cexNodes = 2,
                   cexHubs = 1,
                   cexHubLabels = 6,
                   cexTitle = 9,
                   mar = c(1, 1, 1, 1),
                   labels = NULL,
                   repulsion = 0.0,
                   nodeSizeSpread = 4,
                   edgeTranspHigh = 20,
                   labelFont = 7,
                   labelScale = TRUE
)

core_physeq is my phyloseq object for which i want to make a co-occurence network. The edge lines in the network are not connected node to node, ie. there is some padding. 
![co-occurence_2](https://github.com/microbiome/OMA/assets/110522696/5df846e5-dc60-459f-bf94-6c6de891c27c)

Because of this, the edges between the nodes are becoming confusing. 

Please help me solve this. Thanks in advance.

**Comment by antagomir** [comment]
The OMA gitbook is dedicated to use the data containers `(Tree)SummarizedExperiment` and `MultiAssayExperiment`. The `phyloseq` data container is not supported. Perhaps the problem is related to that?
