### ISSUE TITLE
library(mia) or library("mia")

### ISSUE THREAD

**Issue by TuomasBorman** [microbiome/OMA#563]
https://github.com/microbiome/OMA/pull/562

The library call in OMA should be harmonized. All should be in format library(mia).

**Comment by 0xMuluh** [comment]
This seems to have been resolved for almost all function loads. 
We still have library("BiocManager").

**Comment by TuomasBorman** [comment]
@jkc9886 took this task in https://github.com/microbiome/OMA/issues/564
