### ISSUE TITLE
Styling of packages and functions

### ISSUE THREAD

**Issue by TuomasBorman** [microbiome/OMA#564]
https://github.com/microbiome/OMA/pull/562

All packages should be in format \`package\`, all functions should be in format \`function()\` and all slots should be in format \`assay\`.

Now the book contains multiple different styles. Modify them all to follow this common styling.

**Comment by jkc9886** [comment]
in reference to #562, I can work on maintaining this common styling, just some quick confirmations :

1. should I go with library("mia") or library(mia) ?
2. is it okay to assign you as a reviewer on that PR?

**Comment by antagomir** [comment]
1. use library(mia) style
2. you could add me and @TuomasBorman

**Comment by antagomir** [comment]
Also, @Daenarys8 could provide review comments?

**Comment by jkc9886** [comment]
This issue could be closed @antagomir ?

#584 addressed this.
