### ISSUE TITLE
pseudocount

### ISSUE THREAD

**Issue by TuomasBorman** [microbiome/OMA#566]
In OMA, there is a section about pseudocount. There is no text yet --> add

**Comment by antagomir** [comment]
Can be added but pseudocount is pretty standard thing, just a citation to some available literature/expalnation might be enough, or a short 2-3 sentence explanation. An entire section sounds a bit much to me at least.

**Comment by TuomasBorman** [comment]
I agree, the idea was just couple of sentences and to cite this article for instance https://www.nature.com/articles/nmeth.2897

**Comment by TuomasBorman** [comment]
Maybe we could utilize callout block here. "Important" type might be suitable

**Comment by antagomir** [comment]
yes!
