### ISSUE TITLE
iSEEtree, miaSim

### ISSUE THREAD

**Issue by TuomasBorman** [microbiome/OMA#579]
iSEEtree and miaSim examples are missing from the book. At least, they should be mentioned.

**Comment by antagomir** [comment]
@RiboRings could you suggest citation to iSEEtree in OMA? I think we had a chapter with interactive plots etc. It could fit there. Perhaps a 1-2 sentences or a short paragraph is enough, with a link?

I could do miaSim later, also here just explanation and link should be enough. The miaSim vignette shows how to use it and we should avoid replicating info.

**Comment by antagomir** [comment]
Another option is that we would systematically maintain a list of SE/MAE-related microbiome resources in R/Bioc, similar to what @microsud has done [more generically for any tools includng phyloseq](https://microsud.github.io/Tools-Microbiome-Analysis/). A sort explanation on each pkg could be there.

**Comment by TuomasBorman** [comment]
Interactive plot was in extra visualization chapter and they are moved now to [appendix.](https://microbiome.github.io/OMA/docs/devel/pages/visualization.html#interactive-3d-plots) The other visualization stuff is not worth to put in main chapters, I think. This iSEEtree is important so it should be more visible than it would be in appendix.

I agree that it is not good idea to do overlapping stuff especially when those vignettes are well done.

SE/MAE-related microbiome resources in R/Bioc might be good option. They could go under "Support & Resources" in own chapter so that they are easily found, That list might be something that community could easily extend (might encourage developers to support SE/MAE?)

**Comment by RiboRings** [comment]
I think iSEEtree could fit well the visualisation chapter. I can refer to it there.

In my opinion, we could rethink the visualisation chapter so that it follows the the structure of iSEEtree and the viz options of miaViz.

**Comment by TuomasBorman** [comment]
Yep, but on the other hand most of the techniques in visualization chapter are already covered in main topics. For example, [heatmap section](https://microbiome.github.io/OMA/docs/devel/pages/visualization.html#heatmaps) just shows how to replicate heatmaps with pheatmap, sechm and plain ggplot2.

So we could move visualization back to "main" topics but then the material should be better (no overlapping topics, better structure...).

**Comment by antagomir** [comment]
The problem with a separate visualization chapter is that it gets somewhat disattached from the actual methodological content. Visualization is something that should come across all analyses, and different visualizations are necessary for different analyses.

**Comment by RiboRings** [comment]
> Interactive plot was in extra visualization chapter and they are moved now to [appendix.](https://microbiome.github.io/OMA/docs/devel/pages/visualization.html#interactive-3d-plots) The other visualization stuff is not worth to put in main chapters, I think. This iSEEtree is important so it should be more visible than it would be in appendix.
> 
> I agree that it is not good idea to do overlapping stuff especially when those vignettes are well done.
> 
> SE/MAE-related microbiome resources in R/Bioc might be good option. They could go under "Support & Resources" in own chapter so that they are easily found, That list might be something that community could easily extend (might encourage developers to support SE/MAE?)

I also like this option better

**Comment by antagomir** [comment]
The more general package listing is also related to the following issues:
#191 
#241
#466
#522 
#523

**Comment by antagomir** [comment]
The iSEEtree is now also in [Bioconductor](https://bioconductor.org/packages/devel/bioc/html/iSEEtree.html) and should be linked.

**Comment by RiboRings** [comment]
It was kindly added in "Other relevant packages".

Should we add miaDash to the list in "mia package family"? Is that enough or should we give the link to the web app somewhere? [miadash-microbiome.2.rahtiapp.fi/](https://miadash-microbiome.2.rahtiapp.fi/)

**Comment by antagomir** [comment]
ok to me at least to add on that list.

We can add the link too, I'm open to suggestions..

**Comment by TuomasBorman** [comment]
I think we could have a link. It is nice app and should be easily accessible. Could it be under "2.4. Interactive analysis"? You could describe that we have also graphical interface available. It can be extended. It helps beginners. However, it does not have full functionality provided by Bioconductor. https://microbiome.github.io/OMA/docs/devel/pages/miaverse.html

**Comment by RiboRings** [comment]
Should we close this issue?

**Comment by antagomir** [comment]
Yes, thanks!
