### ISSUE TITLE
Multi-omic chapters to support TreeSE/MAE containers

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#607]
The multiomic chapters do not always show how to do things with the TreeSE/MAE containers. 

Update so that all examples use such data.

Some multiomic functions may not support those containers. In such cases, show how to extract the relevant data from the objects at least.

**Comment by TuomasBorman** [comment]
MAE support for IL is now available https://github.com/himelmallick/IntegratedLearner/pull/13
