### ISSUE TITLE
Clustering examples

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#61]
Aaron Lun has done some nice work on integrating clustering methods with SE class in [bluster](https://www.bioconductor.org/packages/devel/bioc/vignettes/bluster/inst/doc/clusterRows.html). Some examples in OMA could be useful.

**Comment by ChouaibB** [comment]
Would adding an example of [graph-based-clustering](https://www.bioconductor.org/packages/devel/bioc/vignettes/bluster/inst/doc/clusterRows.html#graph-based-clustering) for instance using louvain algorithm at [community-typing](https://microbiome.github.io/OMA/microbiome-community.html#community-typing) be a good place? e.g a subsection titled "Community Detection"

**Comment by ChouaibB** [comment]
When I tried the graph based clustering with PCoA done at the [community-typing](https://microbiome.github.io/OMA/microbiome-community.html#community-typing) section, the following communities were obtained (short-walk vs louvain algorithm):
![image](https://user-images.githubusercontent.com/86964562/128693307-1276d77a-0795-4bfe-8d53-fd3f7397c75f.png)
![image](https://user-images.githubusercontent.com/86964562/128693337-34f17b70-1595-445e-9173-dbfcb19b46c1.png)
