### ISSUE TITLE
Using fido::Pibble on microbiomeDataSets

### ISSUE THREAD

**Issue by ChouaibB** [microbiome/OMA#65]
In an attempt to include more examples about probabilistic modeling/analysis approaches to microbiome data to be available in the book.
`pibble` from the `fido` package offers a  Multinomial Logistic-Normal Linear Regression model ([link](https://jsilve24.github.io/fido/articles/introduction-to-fido.html)), that preforms a fast MAP estimation in combination with parameter uncertainty estimation using Laplace Approximation.
Adding such example using TreeSE to OMA (for instance the Extras section) could be useful?

**Comment by antagomir** [comment]
I think it would be useful. 

This method is for group-wise associations testing based on balances, I would place it in the differential abundance chapter (which is still empty) and under its own subchapter called "Tree-based methods".

**Comment by ChouaibB** [comment]
Sure I'll put a draft there.
