### ISSUE TITLE
Clean Rmd files for certain colData notation

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#83]
Instead of subsetting with
`se[, colData(se)$SampleType=="Feces"]`
one could write just 
`se[, se$SampleType=="Feces"]`

The Rmd files in OMA now often use the longer more complex version.

These could be replaced with the latter, simpler version.

**Comment by antagomir** [comment]
Check and fix accordingly.

In the beginning, in the data manipulation chapter, there can be an example, however, explaining that these two are equivalent.

**Comment by antagomir** [comment]
(I reassigned this from @ake123 to @himmil but if this was already ongoing then just inform us all here)

**Comment by ake123** [comment]
I am working on it
