### ISSUE TITLE
Speed comparisons 

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#85]
Add speed comparisons between `TreeSE` and `phyloseq`. 

This could go to the "Extras" chapter for the time being.

Always check that the output in the two is essentially the same, so that the comparison makes sense.

For each of the comparisons, pick data sets with different numbers of samples from multiple [demo data sets](https://microbiome.github.io/OMA/example-data.html) from small to large, run the same experiments with both containers and provide comparison of times (scatterplot or barplot with data set sample size on X axis, and processing time on Y axis; the results for the two containers can be indicated with different colors in such plot). The data can be converted between the two formats, so it should be straightforward to obtain example data in one format, then convert to the other` format for comparisons.

Comparisons to add:

1. `mia::meltAssay` vs. `phyloseq::psMelt`

2. CLR transformation with `mia::transformSamples(tse)` vs. `microbiome::transform(pseq)`

3. Agglomeration of taxa with `mia::agglomerateByRank(tse)` vs. `phyloseq::tax_glom(pseq)` (also ensure these functions perform the same function, if not let us recheck!)

**Comment by antagomir** [comment]
Hmm perhaps after this, also useful:

4. Beta diversity analysis: drawing PCoA plot as illustrated in both tutorials (CR has example for enterotype data that can do this for both containers) -> This will be very slow for larger data sets, enough to check with smaller ones.

5. Checking alpha diversity for both `microbiome::diversity()` vs. `mia::estimateDiversity()`

**Comment by RiboRings** [comment]
#### Instructions
*number of figures*: 3 + 2
*number of data sets per figure*: at least 3
*ideal number of data sets*: from 5 to 10
*preferably choose*: data sets in TreeSE format with rowTree
*sample sizes*: about 3, 20-80, 100-200, 200-1000, 1000-2000, 2000-10000, 10000 and more
*relatively small data sets*: mia::data("esophagus")
*relatively big data sets*: microbiomeDataSets::GrieneisenTS() and curatedMetagenomicData

**Comment by RiboRings** [comment]
Hey! Just so that you know, I am working on the branch [speed_comparisons](https://github.com/microbiome/OMA/tree/speed_comparisons). I added the Excel file with the raw execution time data [here](https://github.com/microbiome/OMA/tree/speed_comparisons/data) and included draft plots for comparisons 1, 2 and 3 in [Extra](https://github.com/microbiome/OMA/blob/speed_comparisons/99_interactive_3d_plots.Rmd).

**Comment by RiboRings** [comment]
I'd also like to share the scripts I used to run the experiments to make them reproducible, but I'm not sure where to include them.

**Comment by antagomir** [comment]
Can we have an appendix in [course_2021_miaverse](https://microbiome.github.io/course_2021_miaverse/)?

Let us avoid Excel. Kindly output a CSV table from the scripts, this can be browsed in Github directly.

**Comment by antagomir** [comment]
@RiboRings ok you implemented the comparisons earlier. How about just making sure we have a link to the comparisons in some suitable subchapter that mentions phyloseq, for instance in 3.2. One sentence & link is sufficient, we don't have to treat this topic in OMA but linking is good.

**Comment by antagomir** [comment]
@RiboRings can you check this & then close this issue as well, if it is now all ok. 

How about just making sure we have a link to the comparisons in some suitable subchapter that mentions phyloseq, for instance in 3.2. One sentence & link is sufficient, we don't have to treat this topic in OMA but linking to your speed comparison repo is good.
