### ISSUE TITLE
Overview Figure 

### ISSUE THREAD

**Issue by microsud** [microbiome/OMA#90]
![FigureOverview](https://user-images.githubusercontent.com/16476233/134802837-94b8bfb5-b5af-40e5-ac8d-b3b6efbd0377.png)

Just to get a more visual and aesthetic overview for our project :) I can update this as and when we have new packages and ideas.

**Comment by antagomir** [comment]
Yes, very nice! 

Could you add the sources in some public location (under microbiome org) or is that easy/difficulut?

Shall we add this in OMA? 

This also reminds me that we could start creating [cheat sheets](https://github.com/rstudio/cheatsheets) for miaverse packages..

**Comment by microsud** [comment]
I can add this to OMA along with the source. Do yo have a preference for location/folder?

**Comment by antagomir** [comment]
You could see what works best right now, we will still revise these things later in any case. Perhaps somewhere in the Intro chapter to provide some more clarity and motivation?

**Comment by antagomir** [comment]
It is there now.
