### ISSUE TITLE
ordination plots with inter individual variations

### ISSUE THREAD

**Issue by microsud** [microbiome/OMA#95]
Recently, had a discussion about showing inter-individual variation in ordination plots. The figure 1 of this manuscript.
https://cancerpreventionresearch.aacrjournals.org/content/13/5/463

```
library(scater)
library(microbiomeDataSets)
library(ggside)
se <- SprockettTHData()
se <- se[,colData(se)$Country == "Bolivia"]
se <- se[,colData(se)$Sample_Type == "Feces"]
se <- runMDS(se, FUN = vegan::vegdist, name = "MDS_BC", exprs_values = "counts")
p <- plotReducedDim(se, "MDS_BC", colour_by = "Age_Class")
p

# Add explained variance for each axis
e <- attr(reducedDim(se, "MDS_BC"), "eig");
rel_eig <- e/sum(e[e>0])          
p <- p + labs(x = paste("PCoA 1 (", round(100 * rel_eig[[1]],1), "%", ")", sep = ""),
              y = paste("PCoA 2 (", round(100 * rel_eig[[2]],1), "%", ")", sep = "")) + 
  guides(color=guide_legend("Age Group")) 

print(p)

p +
  ggside::geom_xsideboxplot(aes(color=colour_by), 
                              orientation = "y", 
                              width=0.7) +
  ggside::geom_ysideboxplot(aes(color=colour_by), 
                            orientation = "x",
                            width=0.7) +
  ggside::scale_xsidey_discrete() + 
  ggside::scale_ysidex_discrete() 
```
![image](https://user-images.githubusercontent.com/16476233/137633942-2dbed3b7-3799-448c-a3cb-6eac39c5e08e.png)

Should we add this to `OMA` ?

**Comment by antagomir** [comment]
It does not hurt to have material and different examples but this has to balanced with the need to keep the material compact. 

I do not immediately see the clear added value of this visualization but perhaps there could be some. The separation between age groups is here clear also without the boxplots (?)

Should we have supplementary chapters that could include extra material and linked from the relevant chapters; but not necessarily included in the side menu of OMA? Then we could have various complementary examples like this, and at the same time keep the main structure limited to the most common recommended use cases?
