### ISSUE TITLE
Remove function reference chapter?

### ISSUE THREAD

**Issue by antagomir** [microbiome/OMA#99]
We have a [function reference chapter](https://microbiome.github.io/OMA/function-ref.html) in OMA.

This is manually collected and maintained, and could be largelyreplaced by the function references at the respective package websites (see e.g. [miaViz](https://microbiome.github.io/miaViz/reference/index.html)).

Do we have a specific need/justification to keep a separate function reference chapter in OMA? The main thing I am worried about is the need for constant maintenance.

**Comment by antagomir** [comment]
I suggest to remove this unless @TuomasBorman has other suggestions.

**Comment by TuomasBorman** [comment]
Removing is fine for me

This kind of table could be useful but as like this I think there is no value

**Comment by antagomir** [comment]
ready / no? to close when ready

**Comment by ake123** [comment]
Working on it

**Comment by antagomir** [comment]
Removal was approved above. 

Close this and all other issues that have been completed.
